spring:
    datasource:
        url: jdbc:mysql://db:3306/zynodb
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
