version: '3.8'
services:
    app:
        container_name: zyno-spring-app
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/zynodb
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        volumes:
            - .:/app
            - ~/.m2:/root/.m2
            - ~/.gradle:/root/.gradle
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: zynodb
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        command:
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--bind-address=0.0.0.0'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
