version: '3.8'
services:
    app:
        container_name: zynodb
        build:
            context: .
            dockerfile: Dockerfile
            target: runtime
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/zynodb
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: zynodb
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        command:
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--bind-address=0.0.0.0'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
